voting_app_repo: "https://github.com/dockersamples/example-voting-app.git"

voting_app_demo_user: deployuser

voting_app_demo_user_home: "/home/{{ voting_app_demo_user }}"

voting_app_demo_user_dir: "{{ voting_app_demo_user_home }}/Voting-App-Infrastructure-Automation/ansible-automation"

docker_remove_conflicts:
  debian:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
  redhat:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - podman
    - podman-docker

docker_prerequisites:
  debian:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  redhat:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

docker_gpg_key_url:
  debian: "https://download.docker.com/linux/ubuntu/gpg"
  redhat: "https://download.docker.com/linux/centos/gpg"

docker_repo:
  debian: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  redhat: "https://download.docker.com/linux/centos/docker-ce.repo"

docker_packages:
  debian:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  redhat:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
